#!/usr/bin/env python3
"""
Analyze Tier-3 prediction audit outputs generated by highk_alignn_train_v4_30+.

Usage:
  python analyze_tier3_audits.py \
    --audit-dir highk_project/reports/tier3_prediction_audit \
    --out-dir highk_project/reports/tier3_prediction_audit_analysis

Outputs:
  - tier3_audit_summary.md
  - combined_prediction_audit.csv
  - combined_top_errors.csv
  - material_summary_ranked.csv
  - donor_summary_ranked.csv
  - residual_summary.csv
  - suspected_problem_rows.csv

The script is intentionally dependency-light: pandas + numpy only.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


PRED_PATTERNS = ["prediction_audit"]
TOPERR_PATTERNS = ["top20_errors", "top_errors"]
MAT_PATTERNS = ["material_statistics"]
DONOR_PATTERNS = ["donor_statistics"]
RESID_PATTERNS = ["residual_statistics"]


def read_csv_safely(path: Path) -> Optional[pd.DataFrame]:
    try:
        df = pd.read_csv(path)
        df["_source_file"] = path.name
        df["_run_tag"] = infer_run_tag(path.name)
        return df
    except Exception as exc:
        print(f"[WARN] Could not read {path}: {exc}")
        return None


def infer_run_tag(name: str) -> str:
    n = name.replace(".csv", "")
    for suffix in [
        "_prediction_audit",
        "_top20_errors",
        "_top_errors",
        "_material_statistics",
        "_donor_statistics",
        "_residual_statistics",
    ]:
        n = n.replace(suffix, "")
    return n


def find_files(audit_dir: Path, contains_any: List[str]) -> List[Path]:
    files = []
    for p in audit_dir.glob("*.csv"):
        low = p.name.lower()
        if any(tok.lower() in low for tok in contains_any):
            files.append(p)
    return sorted(files)


def concat_files(files: List[Path]) -> pd.DataFrame:
    frames = []
    for f in files:
        df = read_csv_safely(f)
        if df is not None and not df.empty:
            frames.append(df)
    return pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()


def first_existing(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    lower_map = {c.lower(): c for c in df.columns}
    for c in candidates:
        if c in df.columns:
            return c
        if c.lower() in lower_map:
            return lower_map[c.lower()]
    return None


def to_num(s: pd.Series) -> pd.Series:
    return pd.to_numeric(s, errors="coerce")


def add_error_columns(pred: pd.DataFrame) -> pd.DataFrame:
    if pred.empty:
        return pred
    df = pred.copy()
    true_col = first_existing(df, ["k_true", "y_true", "true_k", "target_k", "k_total", "k_measured"])
    pred_col = first_existing(df, ["k_pred", "y_pred", "pred_k", "prediction_k", "k_exp_pred", "k_final_pred"])
    dft_col = first_existing(df, ["k_dft", "k_dft_pred", "dft_pred", "base_k_pred", "k_base_pred"])
    delta_col = first_existing(df, ["delta_pred", "delta_k", "delta_logk", "process_delta", "delta_pred_log"])
    log_true_col = first_existing(df, ["log_true", "y_true_log", "k_true_log", "target_log", "k_total_log_true"])
    log_pred_col = first_existing(df, ["log_pred", "y_pred_log", "k_pred_log", "prediction_log", "k_total_log_pred"])
    if true_col and pred_col:
        df["_k_true"] = to_num(df[true_col])
        df["_k_pred"] = to_num(df[pred_col])
        df["_abs_error"] = (df["_k_pred"] - df["_k_true"]).abs()
        df["_signed_error"] = df["_k_pred"] - df["_k_true"]
        df["_pct_error"] = 100.0 * df["_abs_error"] / df["_k_true"].replace(0, np.nan).abs()
    if dft_col and true_col:
        df["_k_dft"] = to_num(df[dft_col])
        df["_dft_abs_error"] = (df["_k_dft"] - df["_k_true"]).abs()
    if delta_col:
        df["_delta_pred"] = to_num(df[delta_col])
    if log_true_col and log_pred_col:
        df["_log_true"] = to_num(df[log_true_col])
        df["_log_pred"] = to_num(df[log_pred_col])
        df["_log_abs_error"] = (df["_log_pred"] - df["_log_true"]).abs()
    elif true_col and pred_col:
        positive = (df["_k_true"] > 0) & (df["_k_pred"] > 0)
        df.loc[positive, "_log_abs_error"] = (np.log(df.loc[positive, "_k_pred"]) - np.log(df.loc[positive, "_k_true"])).abs()
    if "_dft_abs_error" in df.columns and "_abs_error" in df.columns:
        df["_residual_helped"] = df["_abs_error"] < df["_dft_abs_error"]
        df["_residual_delta_error"] = df["_abs_error"] - df["_dft_abs_error"]
    return df


def summarize_predictions(pred: pd.DataFrame) -> pd.DataFrame:
    if pred.empty or "_abs_error" not in pred.columns:
        return pd.DataFrame()
    rows = []
    for tag, g in pred.groupby("_run_tag", dropna=False):
        valid = g.dropna(subset=["_abs_error"])
        if valid.empty:
            continue
        mad = np.nanmean(np.abs(valid["_k_true"] - np.nanmean(valid["_k_true"]))) if "_k_true" in valid else np.nan
        mae = np.nanmean(valid["_abs_error"])
        rows.append({
            "run_tag": tag,
            "n": len(valid),
            "linear_mae": mae,
            "linear_rmse": np.sqrt(np.nanmean(valid["_abs_error"] ** 2)),
            "k_mad": mad,
            "mad_mae": mad / mae if mae and not np.isnan(mae) else np.nan,
            "log_mae": np.nanmean(valid.get("_log_abs_error", pd.Series(dtype=float))),
            "median_abs_error": np.nanmedian(valid["_abs_error"]),
            "max_abs_error": np.nanmax(valid["_abs_error"]),
            "mean_pct_error": np.nanmean(valid.get("_pct_error", pd.Series(dtype=float))),
            "residual_help_rate_pct": 100.0 * np.nanmean(valid.get("_residual_helped", pd.Series(dtype=float))) if "_residual_helped" in valid else np.nan,
        })
    return pd.DataFrame(rows).sort_values("run_tag")


def ranked_group_summary(pred: pd.DataFrame, group_candidates: List[str], label: str) -> pd.DataFrame:
    if pred.empty or "_abs_error" not in pred.columns:
        return pd.DataFrame()
    group_col = first_existing(pred, group_candidates)
    if group_col is None:
        return pd.DataFrame()
    g = pred.dropna(subset=["_abs_error"]).copy()
    if g.empty:
        return pd.DataFrame()
    out = g.groupby(["_run_tag", group_col], dropna=False).agg(
        n=("_abs_error", "size"),
        mae=("_abs_error", "mean"),
        median_abs_error=("_abs_error", "median"),
        max_abs_error=("_abs_error", "max"),
        mean_true_k=("_k_true", "mean") if "_k_true" in g.columns else ("_abs_error", "size"),
        mean_pred_k=("_k_pred", "mean") if "_k_pred" in g.columns else ("_abs_error", "size"),
    ).reset_index().rename(columns={group_col: label})
    out = out.sort_values(["_run_tag", "mae"], ascending=[True, False])
    return out


def detect_problem_rows(pred: pd.DataFrame) -> pd.DataFrame:
    if pred.empty or "_abs_error" not in pred.columns:
        return pd.DataFrame()
    df = pred.copy()
    flags = []
    for _, r in df.iterrows():
        f = []
        abs_e = r.get("_abs_error", np.nan)
        pct_e = r.get("_pct_error", np.nan)
        if pd.notna(abs_e) and abs_e >= 5:
            f.append("large_abs_error>=5")
        if pd.notna(pct_e) and pct_e >= 25:
            f.append("large_pct_error>=25%")
        if pd.notna(r.get("_residual_delta_error", np.nan)) and r["_residual_delta_error"] > 0:
            f.append("residual_worse_than_dft")
        if pd.notna(r.get("_delta_pred", np.nan)) and abs(r["_delta_pred"]) < 1e-6 and pd.notna(abs_e) and abs_e >= 3:
            f.append("delta_near_zero_but_error_large")
        k_true = r.get("_k_true", np.nan)
        if pd.notna(k_true) and k_true > 35:
            f.append("high_k_true>35")
        flags.append(";".join(f))
    df["triage_flags"] = flags
    keep = df[df["triage_flags"].astype(str).str.len() > 0].copy()
    return keep.sort_values(["_run_tag", "_abs_error"], ascending=[True, False])


def duplicate_process_spread(pred: pd.DataFrame) -> pd.DataFrame:
    if pred.empty or "_k_true" not in pred.columns:
        return pd.DataFrame()
    cols = []
    for candidates in [
        ["material", "material_system", "composition", "formula"],
        ["substrate_temp_C", "ald_substrate_temp_C"],
        ["precursor_type", "precursor_type_Hf"],
        ["oxidant_type"],
        ["anneal_temp_C", "anneal_temp_PDA_C"],
        ["film_thickness_A", "film_thickness_nm"],
    ]:
        c = first_existing(pred, candidates)
        if c:
            cols.append(c)
    if len(cols) < 2:
        return pd.DataFrame()
    g = pred.groupby(["_run_tag"] + cols, dropna=False).agg(
        n=("_k_true", "size"),
        k_min=("_k_true", "min"),
        k_max=("_k_true", "max"),
        k_std=("_k_true", "std"),
        mae=("_abs_error", "mean") if "_abs_error" in pred.columns else ("_k_true", "size"),
    ).reset_index()
    g["k_range"] = g["k_max"] - g["k_min"]
    return g[(g["n"] >= 2) & (g["k_range"] >= 3)].sort_values(["_run_tag", "k_range"], ascending=[True, False])


def write_markdown_report(out_path: Path, pred_summary: pd.DataFrame, material_rank: pd.DataFrame,
                          donor_rank: pd.DataFrame, problem_rows: pd.DataFrame,
                          dup_spread: pd.DataFrame, files_found: Dict[str, int]) -> None:
    lines = []
    lines.append("# Tier-3 audit triage report\n")
    lines.append("## Files found\n")
    for k, v in files_found.items():
        lines.append(f"- {k}: {v}\n")
    lines.append("\n## Overall prediction summary\n")
    if not pred_summary.empty:
        lines.append(pred_summary.to_markdown(index=False))
    else:
        lines.append("No prediction audit summary could be computed. Check column names.\n")

    lines.append("\n\n## Highest-risk materials by MAE\n")
    if not material_rank.empty:
        lines.append(material_rank.groupby("_run_tag").head(10).to_markdown(index=False))
    else:
        lines.append("No material summary available.\n")

    lines.append("\n\n## Highest-risk donors by MAE\n")
    if not donor_rank.empty:
        lines.append(donor_rank.groupby("_run_tag").head(10).to_markdown(index=False))
    else:
        lines.append("No donor summary available.\n")

    lines.append("\n\n## Problem-row triage counts\n")
    if not problem_rows.empty:
        counts = problem_rows.assign(flag=problem_rows["triage_flags"].str.split(";")).explode("flag")
        counts = counts.groupby(["_run_tag", "flag"]).size().reset_index(name="count").sort_values(["_run_tag", "count"], ascending=[True, False])
        lines.append(counts.to_markdown(index=False))
    else:
        lines.append("No flagged problem rows.\n")

    lines.append("\n\n## Duplicate/similar process groups with large k spread\n")
    if not dup_spread.empty:
        lines.append(dup_spread.head(30).to_markdown(index=False))
    else:
        lines.append("No duplicate process groups with k_range >= 3 were found, or required columns are missing.\n")

    lines.append("\n\n## Suggested next actions\n")
    lines.append("1. Inspect `suspected_problem_rows.csv` first; these rows dominate error or residual failure.\n")
    lines.append("2. If `residual_worse_than_dft` is frequent, lower residual LR/bound or keep best_epoch=0.\n")
    lines.append("3. If one donor/phase dominates errors, improve phase-aware donor retrieval for that family.\n")
    lines.append("4. If duplicate process groups have large k spread, the DB lacks variables needed to explain k; curate phase/crystallinity/frequency/electrode/PDA details.\n")
    lines.append("5. Treat N_valid < 20 as directional only; increase verified HfO2/HZO test rows before making claims.\n")
    out_path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--audit-dir", required=True, help="Path to tier3_prediction_audit folder")
    ap.add_argument("--out-dir", default=None, help="Output folder. Default: <audit-dir>/analysis")
    args = ap.parse_args()

    audit_dir = Path(args.audit_dir).expanduser().resolve()
    out_dir = Path(args.out_dir).expanduser().resolve() if args.out_dir else audit_dir / "analysis"
    out_dir.mkdir(parents=True, exist_ok=True)

    pred_files = find_files(audit_dir, PRED_PATTERNS)
    top_files = find_files(audit_dir, TOPERR_PATTERNS)
    mat_files = find_files(audit_dir, MAT_PATTERNS)
    donor_files = find_files(audit_dir, DONOR_PATTERNS)
    resid_files = find_files(audit_dir, RESID_PATTERNS)

    pred = add_error_columns(concat_files(pred_files))
    top = add_error_columns(concat_files(top_files))
    mat = concat_files(mat_files)
    donor = concat_files(donor_files)
    resid = concat_files(resid_files)

    # Computed summaries from prediction audit are more robust than relying on precomputed files.
    pred_summary = summarize_predictions(pred)
    material_rank = ranked_group_summary(pred, ["material", "material_system", "composition", "formula"], "material")
    donor_rank = ranked_group_summary(pred, ["donor_phase", "donor_formula", "imputed_from", "donor_id"], "donor")
    problem_rows = detect_problem_rows(pred)
    dup_spread = duplicate_process_spread(pred)

    pred.to_csv(out_dir / "combined_prediction_audit.csv", index=False)
    if not top.empty:
        top.to_csv(out_dir / "combined_top_errors.csv", index=False)
    if not mat.empty:
        mat.to_csv(out_dir / "raw_material_statistics_combined.csv", index=False)
    if not donor.empty:
        donor.to_csv(out_dir / "raw_donor_statistics_combined.csv", index=False)
    if not resid.empty:
        resid.to_csv(out_dir / "raw_residual_statistics_combined.csv", index=False)
    pred_summary.to_csv(out_dir / "overall_prediction_summary.csv", index=False)
    material_rank.to_csv(out_dir / "material_summary_ranked.csv", index=False)
    donor_rank.to_csv(out_dir / "donor_summary_ranked.csv", index=False)
    problem_rows.to_csv(out_dir / "suspected_problem_rows.csv", index=False)
    dup_spread.to_csv(out_dir / "duplicate_process_k_spread.csv", index=False)

    write_markdown_report(
        out_dir / "tier3_audit_summary.md",
        pred_summary,
        material_rank,
        donor_rank,
        problem_rows,
        dup_spread,
        {
            "prediction_audit CSVs": len(pred_files),
            "top-error CSVs": len(top_files),
            "material-stat CSVs": len(mat_files),
            "donor-stat CSVs": len(donor_files),
            "residual-stat CSVs": len(resid_files),
        },
    )

    print(f"[OK] Wrote analysis outputs to: {out_dir}")
    print(f"[OK] Main report: {out_dir / 'tier3_audit_summary.md'}")
    if not pred_summary.empty:
        print("\nOverall summary:")
        print(pred_summary.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
